const GameData = {
    languages: {
        es: {
            MENU_TITLE: "MENÚ PRINCIPAL",
            CREATE_GAME: "CREAR PARTIDA",
            JOIN_GAME: "UNIRSE A PARTIDA",
            ROOM_CODE_PH: "CÓDIGO DE SALA",
            ROOM: "SALA:",
            PLAYERS: "JUGADORES (Créditos)",
            ROLL_DICE: "TIRAR DADO",
            SURPRISES: "SORPRESAS",
            QUESTIONS: "PREGUNTAS",
            DRAW_CARD: "SACAR CARTA",
            CLOSE: "CERRAR",
            WAITING_PLAYERS: "Esperando jugadores...",
            TURN_OF: "Turno de: ",
            YOUR_TURN: "¡Es tu turno!",
            START_GAME: "INICIAR PARTIDA",
            RESTART_GAME: "REINICIAR",
            LABEL_RENT: "ALQUILER:",
            LABEL_H1: "Con 1 Casa",
            LABEL_H2: "Con 2 Casas",
            LABEL_H3: "Con 3 Casas",
            LABEL_H4: "Con 4 Casas",
            LABEL_HOTEL: "Con HOTEL",
            LABEL_HC: "Coste Casa",
            LABEL_MT: "Valor Hipoteca",
            LABEL_BUY: "COMPRAR POR",
            LABEL_PASS: "PASAR",
            SURPRISES_DESC: "Cae en Cápsula de Suerte para obtener un regalo.",
            QUESTIONS_DESC: "Cae en Pregunta Espacial para ganar créditos.",
            REVEAL_ANSWER: "REVELAR RESPUESTA",
            ANSWER: "RESPUESTA: "
        },
        en: {
            MENU_TITLE: "MAIN MENU",
            CREATE_GAME: "CREATE GAME",
            JOIN_GAME: "JOIN GAME",
            ROOM_CODE_PH: "ROOM CODE",
            ROOM: "ROOM:",
            PLAYERS: "PLAYERS (Credits)",
            ROLL_DICE: "ROLL DICE",
            SURPRISES: "SURPRISES",
            QUESTIONS: "QUESTIONS",
            DRAW_CARD: "DRAW CARD",
            CLOSE: "CLOSE",
            WAITING_PLAYERS: "Waiting for players...",
            TURN_OF: "Turn of: ",
            YOUR_TURN: "It's your turn!",
            START_GAME: "START GAME",
            RESTART_GAME: "RESTART",
            LABEL_RENT: "RENT:",
            LABEL_H1: "With 1 House",
            LABEL_H2: "With 2 Houses",
            LABEL_H3: "With 3 Houses",
            LABEL_H4: "With 4 Houses",
            LABEL_HOTEL: "With HOTEL",
            LABEL_HC: "House Cost",
            LABEL_MT: "Mortgage Value",
            LABEL_BUY: "BUY FOR",
            LABEL_PASS: "PASS",
            SURPRISES_DESC: "Land on Luck Capsule to get a gift.",
            QUESTIONS_DESC: "Land on Space Trivia to win credits.",
            REVEAL_ANSWER: "REVEAL ANSWER",
            ANSWER: "ANSWER: "
        },
        fr: {
            MENU_TITLE: "MENU PRINCIPAL",
            CREATE_GAME: "CRÉER UNE PARTIE",
            JOIN_GAME: "REJOINDRE PARTIE",
            ROOM_CODE_PH: "CODE SALLE",
            ROOM: "SALLE:",
            PLAYERS: "JOUEURS (Crédits)",
            ROLL_DICE: "LANCER LE DÉ",
            SURPRISES: "SURPRISES",
            QUESTIONS: "QUESTIONS",
            DRAW_CARD: "TIRER CARTE",
            CLOSE: "FERMER",
            WAITING_PLAYERS: "En attente de joueurs...",
            TURN_OF: "Tour de : ",
            YOUR_TURN: "C'est votre tour !",
            START_GAME: "DÉMARRER PARTIE",
            RESTART_GAME: "REDÉMARRER",
            LABEL_RENT: "LOYER:",
            LABEL_H1: "Avec 1 Maison",
            LABEL_H2: "Avec 2 Maisons",
            LABEL_H3: "Avec 3 Maisons",
            LABEL_H4: "Avec 4 Maisons",
            LABEL_HOTEL: "Avec HÔTEL",
            LABEL_HC: "Coût Maison",
            LABEL_MT: "Valeur Hypothèque",
            LABEL_BUY: "ACHETER POUR",
            LABEL_PASS: "PASSER",
            SURPRISES_DESC: "Atterrissez sur une Capsule Chance pour un cadeau.",
            QUESTIONS_DESC: "Atterrissez sur Trivia Spatiale pour des crédits.",
            REVEAL_ANSWER: "RÉVÉLER RÉPONSE",
            ANSWER: "RÉPONSE : "
        }
    },
    surprises: [
        { id: "m1", type: "penalty", title: { es: "Exceso de Velocidad Luz", en: "Light Speed Excess", fr: "Excès de Vitessse Lumière" }, text: { es: "Viajabas rápido cerca de nebulosa escolar. Paga 50 CG.", en: "Speeding near school nebula. Pay 50 CG.", fr: "Vitesse excessive près d'une nébuleuse. Payez 50 CG." }, delta: -50 },
        { id: "m2", type: "penalty", title: { es: "Fuga de Oxígeno", en: "Oxygen Leak", fr: "Fuite d'Oxygène" }, text: { es: "Traje espacial con rotura. Paga 100 CG.", en: "Space suit leak. Pay 100 CG.", fr: "Fuite dans la combinaison spatiale. Payez 100 CG." }, delta: -100 },
        { id: "m3", type: "penalty", title: { es: "Mantenimiento Orbital", en: "Orbital Maintenance", fr: "Maintenance Orbitale" }, text: { es: "Tasa de mantenimiento: 25 CG por propiedad.", en: "Maintenance fee: 25 CG per property.", fr: "Frais de maintenance : 25 CG par propriété." }, delta: -25 },
        { id: "m4", type: "penalty", title: { es: "Peaje de Agujero de Gusano", en: "Wormhole Toll", fr: "Péage Trou de Ver" }, text: { es: "Atajo ilegal, policía te atrapó. Paga 40 CG.", en: "Illegal shortcut caught. Pay 40 CG.", fr: "Raccourci illégal détecté. Payez 40 CG." }, delta: -40 },
        { id: "m5", type: "penalty", title: { es: "Basura Espacial", en: "Space Junk", fr: "Déchets Spatiaux" }, text: { es: "Cohetes ensuciaron órbita. 10 CG a cada jugador.", en: "Pay 10 CG to each player.", fr: "Payez 10 CG à chaque joueur." }, delta: -10 },
        { id: "m6", type: "penalty", title: { es: "Estacionamiento Ilegal", en: "Illegal Parking", fr: "Stationnement Illégal" }, text: { es: "Nave en zona restringida. Paga 75 CG.", en: "Parking in restricted zone. Pay 75 CG.", fr: "Stationnement zone interdite. Payez 75 CG." }, delta: -75 },
        { id: "m7", type: "penalty", title: { es: "Contaminación de Nebulosa", en: "Nebula Pollution", fr: "Pollution de Nébuleuse" }, text: { es: "Residuos en nebulosa protegida. Paga 150 CG.", en: "Waste in protected nebula. Pay 150 CG.", fr: "Déchets en zone protégée. Payez 150 CG." }, delta: -150 },
        { id: "m8", type: "penalty", title: { es: "Contrabando de Meteoritos", en: "Meteorite Contraband", fr: "Contrebande de Météorites" }, text: { es: "Meteoritos no declarados. Paga 80 CG.", en: "Undeclared meteorites. Pay 80 CG.", fr: "Météorites non déclarées. Payez 80 CG." }, delta: -80 },
        { id: "m9", type: "penalty", title: { es: "Fallo de Navegación", en: "Navigation Error", fr: "Erreur de Navigation" }, text: { es: "Te saliste de tu ruta. Paga 60 CG.", en: "Off route error. Pay 60 CG.", fr: "Erreur de parcours. Payez 60 CG." }, delta: -60 },
        { id: "m10", type: "penalty", title: { es: "Territorio Alienígena", en: "Alien Territory", fr: "Territoire Alien" }, text: { es: "Entraste a zona protegida. Paga 200 CG.", en: "Restricted alien zone. Pay 200 CG.", fr: "Zone alien restreinte. Payez 200 CG." }, delta: -200 },
        { id: "m11", type: "penalty", title: { es: "Impuestos Cósmicos", en: "Cosmic Taxes", fr: "Impôts Cosmiques" }, text: { es: "Irregularidades fiscales. Paga 120 CG.", en: "Tax issues found. Pay 120 CG.", fr: "Irrégularités fiscales. Payez 120 CG." }, delta: -120 },
        { id: "m12", type: "penalty", title: { es: "Equipaje Interestelar", en: "Interstellar Luggage", fr: "Bagages Interstellaires" }, text: { es: "Exceso de peso. 30 CG por propiedad.", en: "Overweight ship fee. 30 CG per property.", fr: "Excès de bagages. 30 CG par propriété." }, delta: -30 },
        { id: "m13", type: "penalty", title: { es: "Campo Magnético", en: "Magnetic Field", fr: "Champ Magnétique" }, text: { es: "Experimentos alteraron frecuencia. Paga 90 CG.", en: "Frequency disturbance. Pay 90 CG.", fr: "Perturbation magnétique. Payez 90 CG." }, delta: -90 },
        { id: "m14", type: "penalty", title: { es: "Caza Ilegal", en: "Illegal Hunting", fr: "Chasse Illégale" }, text: { es: "Cometa capturado sin permiso. Paga 70 CG.", en: "Illegal comet hunt. Pay 70 CG.", fr: "Chasse illégale comète. Payez 70 CG." }, delta: -70 },
        { id: "m15", type: "penalty", title: { es: "Ruido Cósmico", en: "Cosmic Noise", fr: "Bruit Cosmique" }, text: { es: "Interferiste señales. Paga 45 CG.", en: "Signal interference. Pay 45 CG.", fr: "Interférence signal. Payez 45 CG." }, delta: -45 },
        { id: "m16", type: "penalty", title: { es: "Destrucción de Satélite", en: "Satellite Crash", fr: "Collision Satellite" }, text: { es: "Colisionaste con satélite. Paga 100 CG.", en: "Collided with satellite. Pay 100 CG.", fr: "Collision avec satellite. Payez 100 CG." }, delta: -100 },
        { id: "m17", type: "penalty", title: { es: "Violación de Cuarentena", en: "Quarantine Breach", fr: "Viol de Quarantaine" }, text: { es: "Saliste sin autorización. Paga 180 CG.", en: "Unauthorized exit. Pay 180 CG.", fr: "Sortie non autorisée. Payez 180 CG." }, delta: -180 },
        { id: "m18", type: "penalty", title: { es: "Minería Ilegal", en: "Illegal Mining", fr: "Minage Illégal" }, text: { es: "Sin licencia de minería. Paga 130 CG.", en: "No mining license. Pay 130 CG.", fr: "Sans licence de mine. Payez 130 CG." }, delta: -130 },
        { id: "m19", type: "penalty", title: { es: "Daños Galácticos", en: "Galactic Damage", fr: "Détérioration Galaxie" }, text: { es: "Experimentos dañaron la Vía Láctea. Paga 250 CG.", en: "Galaxy damage. Pay 250 CG.", fr: "Dégâts galaxie. Payez 250 CG." }, delta: -250 },
        { id: "m20", type: "penalty", title: { es: "Turismo Ilegal", en: "Illegal Tourism", fr: "Tourisme Illégal" }, text: { es: "Viajes sin licencia. Paga 95 CG.", en: "Unlicensed tours. Pay 95 CG.", fr: "Voyages sans licence. Payez 95 CG." }, delta: -95 },
        { id: "m21", type: "penalty", title: { es: "Socorro Ignorado", en: "Rescue Ignored", fr: "Secours Ignoré" }, text: { es: "No respondiste a alerta. 50 CG a cada jugador.", en: "Ignored SOS. Pay 50 CG to each player.", fr: "SOS ignoré. Payez 50 CG à chaque joueur." }, delta: -50 },
        { id: "m22", type: "penalty", title: { es: "Especies Prohibidas", en: "Illegal Species", fr: "Espèces Interdites" }, text: { es: "Vida alienígena sin permiso. Paga 160 CG.", en: "Alien life smuggling. Pay 160 CG.", fr: "Trafic de vie alien. Payez 160 CG." }, delta: -160 },
        { id: "m23", type: "penalty", title: { es: "Seguro Espacial", en: "No Insurance", fr: "Pas d'Assurance" }, text: { es: "Seguro vencido. Paga 85 CG.", en: "Expired insurance. Pay 85 CG.", fr: "Assurance expirée. Payez 85 CG." }, delta: -85 },
        { id: "m24", type: "penalty", title: { es: "Clima Alterado", en: "Climate Altered", fr: "Climat Changé" }, text: { es: "Geoingeniería fallida. Paga 200 CG.", en: "Failed geoengineering. Pay 200 CG.", fr: "Géoingénierie échouée. Payez 200 CG." }, delta: -200 },
        { id: "m25", type: "penalty", title: { es: "Piratería", en: "Piracy", fr: "Piraterie" }, text: { es: "Interceptaste señales. Paga 110 CG.", en: "Signal piracy. Pay 110 CG.", fr: "Piratage signaux. Payez 110 CG." }, delta: -110 },

        { id: "o26", type: "reward", title: { es: "Devolución de Impuestos", en: "Tax Refund", fr: "Remboursement Impôts" }, text: { es: "Cálculo a tu favor. Recibe 100 CG.", en: "Tax credit. Get 100 CG.", fr: "Crédit d'impôt. Recevez 100 CG." }, delta: 100 },
        { id: "o27", type: "reward", title: { es: "Lotería Espacial", en: "Space Lottery", fr: "Loterie Spatiale" }, text: { es: "Has ganado el segundo premio. Recibe 200 CG.", en: "Second prize winner. Get 200 CG.", fr: "Gagnant du 2ème prix. Recevez 200 CG." }, delta: 200 },
        { id: "o28", type: "reward", title: { es: "Venta de Datos", en: "Data Sale", fr: "Vente de Données" }, text: { es: "Vendiste info de cometa. Recibe 50 CG.", en: "Sold comet data. Get 50 CG.", fr: "Vente infos comète. Recevez 50 CG." }, delta: 50 },
        { id: "o29", type: "reward", title: { es: "Herencia", en: "Inheritance", fr: "Héritage" }, text: { es: "Pariente de galaxia lejana te deja 150 CG.", en: "Fortune from distant relative. Get 150 CG.", fr: "Héritage lointaine galaxie. Recevez 150 CG." }, delta: 150 },
        { id: "o30", type: "reward", title: { es: "Nuevo Planeta", en: "New Planet", fr: "Nouvelle Planète" }, text: { es: "Planeta habitable encontrado. Recibe 300 CG.", en: "Habitable planet found. Get 300 CG.", fr: "Planète habitable trouvée. Recevez 300 CG." }, delta: 300 },
        { id: "o31", type: "reward", title: { es: "Rescate", en: "Rescue Reward", fr: "Prime de Secours" }, text: { es: "Ayudaste a nave averiada. Recibe 80 CG.", en: "Helped distressed ship. Get 80 CG.", fr: "Secours vaisseau. Recevez 80 CG." }, delta: 80 },
        { id: "o32", type: "reward", title: { es: "Minería Asteroide", en: "Asteroid Mining", fr: "Minage Astéroïde" }, text: { es: "Metales preciosos hallados. Recibe 175 CG.", en: "Precious metals found. Get 175 CG.", fr: "Métaux précieux trouvés. Recevez 175 CG." }, delta: 175 },
        { id: "o33", type: "reward", title: { es: "Beca Academia", en: "Academy Grant", fr: "Bourse Académie" }, text: { es: "Beca de estudios espacial. Recibe 120 CG.", en: "Space study grant. Get 120 CG.", fr: "Bourse d'études. Recevez 120 CG." }, delta: 120 },
        { id: "o34", type: "reward", title: { es: "Premio Nobel", en: "Nobel Prize", fr: "Prix Nobel" }, text: { es: "Excelencia científica. Recibe 250 CG.", en: "Scientific excellence. Get 250 CG.", fr: "Excellence scientifique. Recevez 250 CG." }, delta: 250 },
        { id: "o35", type: "reward", title: { es: "Cultura Antigua", en: "Ancient Culture", fr: "Culture Ancienne" }, text: { es: "Artefactos antiguos hallados. Recibe 180 CG.", en: "Old artifacts found. Get 180 CG.", fr: "Artefacts trouvés. Recevez 180 CG." }, delta: 180 },
        { id: "o36", type: "reward", title: { es: "Reembolso Fuel", en: "Fuel Refund", fr: "Remboursement Carburant" }, text: { es: "Error en factura. Recibe 60 CG.", en: "Fuel bill error refund. Get 60 CG.", fr: "Erreur facturation. Recevez 60 CG." }, delta: 60 },
        { id: "o37", type: "reward", title: { es: "Patrocinio", en: "Sponsorship", fr: "Parrainage" }, text: { es: "Contrato publicitario. Recibe 140 CG.", en: "Advertising contract. Get 140 CG.", fr: "Contrat pub. Recevez 140 CG." }, delta: 140 },
        { id: "o38", type: "reward", title: { es: "Captura Pirata", en: "Pirate Bounty", fr: "Prime Pirate" }, text: { es: "Buscado capturado. Recibe 220 CG.", en: "Wanted pirate captured. Get 220 CG.", fr: "Pirate capturé. Recevez 220 CG." }, delta: 220 },
        { id: "o39", type: "reward", title: { es: "Inversión Cripto", en: "Crypto Profit", fr: "Profil Crypto" }, text: { es: "Beneficios de LunaCoin. Recibe 90 CG.", en: "LunaCoin gains. Get 90 CG.", fr: "Gains LunaCoin. Recevez 90 CG." }, delta: 90 },
        { id: "o40", type: "reward", title: { es: "Derechos de Autor", en: "Copyright", fr: "Droits d'Auteur" }, text: { es: "Tu canción es un éxito. Recibe 110 CG.", en: "Music hit royalties. Get 110 CG.", fr: "Succès musical. Recevez 110 CG." }, delta: 110 },
        { id: "o41", type: "reward", title: { es: "Subvención", en: "Grant", fr: "Subvention" }, text: { es: "Fondos de investigación. Recibe 130 CG.", en: "Research funding. Get 130 CG.", fr: "Aide recherche. Recevez 130 CG." }, delta: 130 },
        { id: "o42", type: "reward", title: { es: "Cristales", en: "Energy Crystals", fr: "Cristaux d'Énergie" }, text: { es: "Energía pura hallada. Recibe 160 CG.", en: "Pure energy found. Get 160 CG.", fr: "Énergie pure. Recevez 160 CG." }, delta: 160 },
        { id: "o43", type: "reward", title: { es: "Consultoría", en: "Consultancy", fr: "Consultance" }, text: { es: "Servicios astrográficos. Recibe 100 CG.", en: "Astro consulting paid. Get 100 CG.", fr: "Consultance payée. Recevez 100 CG." }, delta: 100 },
        { id: "o44", type: "reward", title: { es: "Supervivencia", en: "Survival", fr: "Survie" }, text: { es: "Tormenta solar superada. Recibe 70 CG.", en: "Solar storm survived. Get 70 CG.", fr: "Survie tempête solaire. Recevez 70 CG." }, delta: 70 },
        { id: "o45", type: "reward", title: { es: "Venta de Arte", en: "Art Sale", fr: "Vente d'Art" }, text: { es: "Obra vendida en subasta. Recibe 190 CG.", en: "Auction art sale. Get 190 CG.", fr: "Vente aux enchères. Recevez 190 CG." }, delta: 190 },
        { id: "o46", type: "reward", title: { es: "Minería Pro", en: "Pro Mining", fr: "Minage Pro" }, text: { es: "Derechos exclusivos. Recibe 40 CG.", en: "Exclusive rights grant. Get 40 CG.", fr: "Droits exclusifs. Recevez 40 CG." }, delta: 40 },
        { id: "o47", type: "reward", title: { es: "TV Estelar", en: "Star TV", fr: "Télé Stellaire" }, text: { es: "Audiencia máxima. Recibe 135 CG.", en: "Max rating profits. Get 135 CG.", fr: "Audience record. Recevez 135 CG." }, delta: 135 },
        { id: "o48", type: "reward", title: { es: "Nave Antigua", en: "Old Ship", fr: "Vieux Vaisseau" }, text: { es: "Restauración exitosa. Recibe 85 CG.", en: "Successful restoration. Get 85 CG.", fr: "Restauration réussie. Recevez 85 CG." }, delta: 85 },
        { id: "o49", type: "reward", title: { es: "Energía Nueva", en: "New Energy", fr: "Nouvelle Énergie" }, text: { es: "Descubrimiento renovable. Recibe 250 CG.", en: "Renewable discovery. Get 250 CG.", fr: "Découverte renouvelable. Recevez 250 CG." }, delta: 250 },
        { id: "o50", type: "reward", title: { es: "Gran Premio", en: "Grand Prize", fr: "Grand Prix" }, text: { es: "¡Viajero del Año! Recibe 300 CG.", en: "Traveler of the year. Get 300 CG.", fr: "Voyageur de l'année. Recevez 300 CG." }, delta: 300 }
    ],
    questions: [
        { id: "q1", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cuál es el planeta más grande del Sistema Solar?", en: "Which is the largest planet in the Solar System?", fr: "Quelle est la plus grande planète du système solaire ?" }, answer: { es: "Júpiter", en: "Jupiter", fr: "Jupiter" }, reward: 50, penalty: -30 },
        { id: "q2", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cómo se llama nuestra galaxia?", en: "What is the name of our galaxy?", fr: "Comment s'appelle notre galaxie ?" }, answer: { es: "Vía Láctea", en: "Milky Way", fr: "Voie Lactée" }, reward: 50, penalty: -30 },
        { id: "q3", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿El Sol es un planeta?", en: "Is the Sun a planet?", fr: "Le Soleil est-il une planète ?" }, answer: { es: "Falso (es una estrella)", en: "False (it's a star)", fr: "Faux (c'est une étoile)" }, reward: 20, penalty: -20 },
        { id: "q4", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué planeta es conocido como el Planeta Rojo?", en: "Which planet is known as the Red Planet?", fr: "Quelle planète est connue comme la planète rouge ?" }, answer: { es: "Marte", en: "Mars", fr: "Mars" }, reward: 50, penalty: -30 },
        { id: "q5", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cuánto tarda la luz solar en llegar a la Tierra?", en: "How long does sunlight take to reach Earth?", fr: "Combien de temps met la lumière du soleil pour atteindre la Terre ?" }, answer: { es: "8 minutos", en: "8 minutes", fr: "8 minutes" }, reward: 100, penalty: -50 },
        { id: "q6", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Quién fue el primero en pisar la Luna?", en: "Who was the first person on the Moon?", fr: "Qui a été le premier sur la Lune ?" }, answer: { es: "Neil Armstrong", en: "Neil Armstrong", fr: "Neil Armstrong" }, reward: 50, penalty: -30 },
        { id: "q7", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cuál es el planeta más cercano al Sol?", en: "Which planet is closest to the Sun?", fr: "Quelle est la planète la plus proche du soleil ?" }, answer: { es: "Mercurio", en: "Mercury", fr: "Mercure" }, reward: 40, penalty: -20 },
        { id: "q8", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué cuerpo dejó de ser planeta en 2006?", en: "Which body stopped being a planet in 2006?", fr: "Quel corps céleste n'est plus une planète depuis 2006 ?" }, answer: { es: "Plutón", en: "Pluto", fr: "Pluton" }, reward: 50, penalty: -30 },
        { id: "q9", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué fuerza nos mantiene en el suelo?", en: "What force keeps us on the ground?", fr: "Quelle force nous maintient au sol ?" }, answer: { es: "La Gravedad", en: "Gravity", fr: "La Gravité" }, reward: 40, penalty: -20 },
        { id: "q10", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cuántas lunas tiene Marte?", en: "How many moons does Mars have?", fr: "Combien de lunes a Mars ?" }, answer: { es: "2 (Fobos y Deimos)", en: "2 (Phobos and Deimos)", fr: "2 (Phobos et Déimos)" }, reward: 35, penalty: -20 },
        { id: "q11", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Estrella más cercana después del Sol?", en: "Closest star after the Sun?", fr: "Étoile la plus proche après le Soleil ?" }, answer: { es: "Proxima Centauri", en: "Proxima Centauri", fr: "Proxima Centauri" }, reward: 75, penalty: -40 },
        { id: "q12", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Anillos más visibles?", en: "Which planet has the most visible rings?", fr: "Quelle planète a les anneaux les plus visibles ?" }, answer: { es: "Saturno", en: "Saturn", fr: "Saturne" }, reward: 50, penalty: -30 },
        { id: "q13", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cuál es el planeta más caliente?", en: "Which is the hottest planet?", fr: "Quelle est la planète la plus chaude ?" }, answer: { es: "Venus", en: "Venus", fr: "Vénus" }, reward: 60, penalty: -30 },
        { id: "q14", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cuántos planetas hay en el Sistema Solar?", en: "How many planets are there?", fr: "Combien y a-t-il de planètes ?" }, answer: { es: "8", en: "8", fr: "8" }, reward: 45, penalty: -20 },
        { id: "q15", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué es un agujero negro?", en: "What is a black hole?", fr: "Qu'est-ce qu'un trou noir ?" }, answer: { es: "Región con gravedad extrema", en: "Region with extreme gravity", fr: "Région à gravité extrême" }, reward: 50, penalty: -30 },
        { id: "q16", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cuál es la luna más grande?", en: "Which is the largest moon?", fr: "Quelle est la plus grande lune ?" }, answer: { es: "Ganimedes (Júpiter)", en: "Ganymede (Jupiter)", fr: "Ganymède (Jupiter)" }, reward: 80, penalty: -40 },
        { id: "q17", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué planeta gira de lado?", en: "Which planet rotates sideways?", fr: "Quelle planète tourne sur le côté ?" }, answer: { es: "Urano", en: "Uranus", fr: "Uranus" }, reward: 55, penalty: -30 },
        { id: "q18", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cuánto dura un día en Júpiter?", en: "How long is a day on Jupiter?", fr: "Quelle est la durée d'un jour sur Jupiter ?" }, answer: { es: "~10 horas", en: "~10 hours", fr: "~10 heures" }, reward: 50, penalty: -30 },
        { id: "q19", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué es la Vía Láctea?", en: "What is the Milky Way?", fr: "Qu'est-ce que la Voie Lactée ?" }, answer: { es: "Nuestra galaxia", en: "Our galaxy", fr: "Notre galaxie" }, reward: 30, penalty: -15 },
        { id: "q20", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Segundo planeta más grande?", en: "Second largest planet?", fr: "Deuxième plus grande planète ?" }, answer: { es: "Saturno", en: "Saturn", fr: "Saturne" }, reward: 65, penalty: -35 },
        { id: "q21", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué planeta es el Planeta Azul?", en: "Which is the Blue Planet?", fr: "Quelle est la planète bleue ?" }, answer: { es: "Neptuno (según PDF)", en: "Neptune", fr: "Neptune" }, reward: 50, penalty: -25 },
        { id: "q22", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cuántos satélites tiene Júpiter?", en: "Moons of Jupiter count?", fr: "Nombre de lunes de Jupiter ?" }, answer: { es: "Más de 95", en: "More than 95", fr: "Plus de 95" }, reward: 90, penalty: -45 },
        { id: "q23", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué es una supernova?", en: "What is a supernova?", fr: "Qu'est-ce qu'une supernova ?" }, answer: { es: "Explosión de una estrella", en: "Star explosion", fr: "Explosion d'une étoile" }, reward: 70, penalty: -35 },
        { id: "q24", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Planeta más pequeño?", en: "Smallest planet?", fr: "Plus petite planète ?" }, answer: { es: "Mercurio", en: "Mercury", fr: "Mercure" }, reward: 40, penalty: -20 },
        { id: "q25", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Dónde está el Olympus Mons?", en: "Where is Olympus Mons?", fr: "Où est Olympus Mons ?" }, answer: { es: "Marte", en: "Mars", fr: "Mars" }, reward: 70, penalty: -35 },
        { id: "q26", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Giro Tierra/Sol?", en: "Earth orbit time?", fr: "Temps orbite terrestre ?" }, answer: { es: "365 días", en: "365 days", fr: "365 jours" }, reward: 40, penalty: -20 },
        { id: "q27", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué es un asteroide?", en: "What is an asteroid?", fr: "Qu'est-ce qu'un astéroïde ?" }, answer: { es: "Cuerpo rocoso", en: "Rocky body", fr: "Corps rocheux" }, reward: 25, penalty: -15 },
        { id: "q28", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Atmósfera densa?", en: "Densest planet atmosphere?", fr: "Atmosphère plus dense ?" }, answer: { es: "Venus", en: "Venus", fr: "Vénus" }, reward: 55, penalty: -30 },
        { id: "q29", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Primera mujer?", en: "First woman in space?", fr: "Première femme dans l'espace ?" }, answer: { es: "Valentina Tereshkova", en: "Valentina Tereshkova", fr: "Valentina Tereshkova" }, reward: 60, penalty: -30 },
        { id: "q30", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cinturón asteroides?", en: "Where is the asteroid belt?", fr: "Où est la ceinture d'astéroïdes ?" }, answer: { es: "Región entre Marte y Júpiter", en: "Between Mars and Jupiter", fr: "Entre Mars et Jupiter" }, reward: 45, penalty: -25 },
        { id: "q31", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué planeta tiene el día más largo?", en: "Which planet has the longest day?", fr: "Quel jour est le plus long ?" }, answer: { es: "Venus (243 días)", en: "Venus (243 days)", fr: "Vénus (243 jours)" }, reward: 50, penalty: -25 },
        { id: "q32", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Estrellas fugaces?", en: "What are shooting stars?", fr: "Étoiles filantes ?" }, answer: { es: "Meteoros en la atmósfera", en: "Meteors in the atmosphere", fr: "Météores dans l'atmosphère" }, reward: 30, penalty: -15 },
        { id: "q33", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Temp. Sol?", en: "Sun surface temp?", fr: "Température Soleil ?" }, answer: { es: "~5,500°C", en: "~5,500°C", fr: "~5,500°C" }, reward: 85, penalty: -45 },
        { id: "q34", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Hermano Tierra?", en: "Earth's twin planet?", fr: "Jumeau de la Terre ?" }, answer: { es: "Venus", en: "Venus", fr: "Vénus" }, reward: 50, penalty: -25 },
        { id: "q35", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué es un cometa?", en: "What is a comet?", fr: "Qu'est-ce qu'une comète ?" }, answer: { es: "Cuerpo helado con gas", en: "Icy body with gas", fr: "Corps de glace et gaz" }, reward: 40, penalty: -20 },
        { id: "q36", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Más lejano Sol?", en: "Farthest from Sun?", fr: "Plus loin du Soleil ?" }, answer: { es: "Neptuno", en: "Neptune", fr: "Neptune" }, reward: 50, penalty: -25 },
        { id: "q37", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué es la EEI?", en: "What is the ISS?", fr: "C'est quoi l'ISS ?" }, answer: { es: "Laboratorio orbital", en: "Orbital lab", fr: "Laboratoire orbital" }, reward: 50, penalty: -25 },
        { id: "q38", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Lunas Neptuno?", en: "How many moons does Neptune have?", fr: "Lunes de Neptune ?" }, answer: { es: "14", en: "14", fr: "14" }, reward: 60, penalty: -30 },
        { id: "q39", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Vientos rápidos?", en: "Fastest wind planet?", fr: "Vents plus rapides ?" }, answer: { es: "Neptuno (2,100 km/h)", en: "Neptune (2,100 km/h)", fr: "Neptune (2,100 km/h)" }, reward: 60, penalty: -30 },
        { id: "q40", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Qué es una nebulosa?", en: "What is a nebula?", fr: "Une nébuleuse ?" }, answer: { es: "Nube de gas y nido estelar", en: "Gas cloud and star nursery", fr: "Nuage de gaz et pouponnière" }, reward: 100, penalty: -50 },
        { id: "q41", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Color Sol?", en: "Real color of the Sun?", fr: "Couleur du Soleil ?" }, answer: { es: "Blanco", en: "White", fr: "Blanc" }, reward: 40, penalty: -25 },
        { id: "q42", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Planetas Sol-Tierra?", en: "Planets between Sun and Earth?", fr: "Planètes entre Soleil et Terre ?" }, answer: { es: "2 (Mercurio y Venus)", en: "2 (Mercury and Venus)", fr: "2 (Mercure et Vénus)" }, reward: 35, penalty: -30 },
        { id: "q43", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Luna Planeta?", en: "Is Moon a planet?", fr: "Lune planète ?" }, answer: { es: "No, es un satélite", en: "No, a satellite", fr: "Non, un satellite" }, reward: 30, penalty: -20 },
        { id: "q44", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Destaque anillos?", en: "Known for rings?", fr: "Connu pour anneaux ?" }, answer: { es: "Saturno", en: "Saturn", fr: "Saturne" }, reward: 45, penalty: -35 },
        { id: "q45", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Tierra plana?", en: "Round or flat Earth?", fr: "Terre ronde ou plate ?" }, answer: { es: "Redonda", en: "Round", fr: "Ronde" }, reward: 25, penalty: -70 },
        { id: "q46", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cielo noche?", en: "In the night sky?", fr: "Ciel de nuit ?" }, answer: { es: "La Luna y las estrellas", en: "The Moon and stars", fr: "La Lune et les étoiles" }, reward: 30, penalty: -15 },
        { id: "q47", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Lunas Tierra?", en: "How many moons for Earth?", fr: "Lunes de la Terre ?" }, answer: { es: "1", en: "1", fr: "1" }, reward: 35, penalty: -25 },
        { id: "q48", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Sol Estrella?", en: "Is Sun star or planet?", fr: "Soleil étoile ?" }, answer: { es: "Estrella", en: "Star", fr: "Étoile" }, reward: 40, penalty: -50 },
        { id: "q49", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Cercano Tierra?", en: "Closest planet to Earth?", fr: "Plus proche Terre ?" }, answer: { es: "Venus", en: "Venus", fr: "Vénus" }, reward: 50, penalty: -40 },
        { id: "q50", title: { es: "Desafío Cósmico", en: "Cosmic Challenge", fr: "Défi Cosmique" }, text: { es: "¿Planeta Rojo?", en: "What is the Red Planet?", fr: "Quelle est la planète rouge ?" }, answer: { es: "Marte", en: "Mars", fr: "Mars" }, reward: 45, penalty: -30 }
    ],
    // 28 tiles board (8x8 outline)
    board: [
        { name: "START", type: "corner" }, // 0
        { name: "La Luna", type: "property", color: "brown", price: 60, baseRent: 2, rent1: 10, rent2: 30, rent3: 90, rent4: 160, rentHotel: 250, houseCost: 50, mortgage: 30 }, // 1
        { name: "Marte", type: "property", color: "brown", price: 80, baseRent: 5, rent1: 27, rent2: 80, rent3: 240, rent4: 427, rentHotel: 600, houseCost: 67, mortgage: 40 }, // 2
        { name: "CÁPSULA DE SUERTE", type: "action", subType: "surprise" }, // 3
        { name: "Mercurio", type: "property", color: "lightblue", price: 100, baseRent: 6, rent1: 30, rent2: 90, rent3: 270, rent4: 400, rentHotel: 550, houseCost: 50, mortgage: 50 }, // 4
        { name: "Venus", type: "property", color: "lightblue", price: 120, baseRent: 8, rent1: 40, rent2: 100, rent3: 300, rent4: 450, rentHotel: 600, houseCost: 50, mortgage: 60 }, // 5
        { name: "Europa (Satélite)", type: "property", color: "pink", price: 140, baseRent: 10, rent1: 50, rent2: 150, rent3: 450, rent4: 625, rentHotel: 750, houseCost: 100, mortgage: 70 }, // 6
        { name: "JUST VISITING", type: "corner" }, // 7
        { name: "Júpiter", type: "property", color: "pink", price: 140, baseRent: 10, rent1: 50, rent2: 150, rent3: 450, rent4: 625, rentHotel: 750, houseCost: 100, mortgage: 70 }, // 8
        { name: "Saturno", type: "property", color: "pink", price: 160, baseRent: 12, rent1: 60, rent2: 180, rent3: 500, rent4: 700, rentHotel: 900, houseCost: 100, mortgage: 80 }, // 9
        { name: "PREGUNTA ESPACIAL", type: "action", subType: "question" }, // 10
        { name: "Titán", type: "property", color: "orange", price: 180, baseRent: 14, rent1: 70, rent2: 200, rent3: 550, rent4: 750, rentHotel: 950, houseCost: 100, mortgage: 90 }, // 11
        { name: "Urano", type: "property", color: "orange", price: 180, baseRent: 14, rent1: 70, rent2: 200, rent3: 550, rent4: 750, rentHotel: 950, houseCost: 100, mortgage: 90 }, // 12
        { name: "Neptuno", type: "property", color: "orange", price: 200, baseRent: 16, rent1: 80, rent2: 220, rent3: 600, rent4: 800, rentHotel: 1000, houseCost: 100, mortgage: 100 }, // 13
        { name: "O2 SUPPLIES", type: "corner" }, // 14
        { name: "Plutón", type: "property", color: "red", price: 220, baseRent: 18, rent1: 90, rent2: 250, rent3: 700, rent4: 875, rentHotel: 1050, houseCost: 150, mortgage: 110 }, // 15
        { name: "Cinturón de Asteroides", type: "property", color: "red", price: 220, baseRent: 18, rent1: 90, rent2: 250, rent3: 700, rent4: 875, rentHotel: 1050, houseCost: 150, mortgage: 110 }, // 16
        { name: "CÁPSULA DE SUERTE", type: "action", subType: "surprise" }, // 17
        { name: "Nube de Oort", type: "property", color: "red", price: 240, baseRent: 20, rent1: 100, rent2: 300, rent3: 750, rent4: 925, rentHotel: 1100, houseCost: 150, mortgage: 120 }, // 18
        { name: "Próxima Centauri", type: "property", color: "yellow", price: 260, baseRent: 22, rent1: 110, rent2: 330, rent3: 800, rent4: 975, rentHotel: 1150, houseCost: 150, mortgage: 130 }, // 19
        { name: "Alpha Centauri", type: "property", color: "yellow", price: 260, baseRent: 22, rent1: 110, rent2: 330, rent3: 800, rent4: 975, rentHotel: 1150, houseCost: 150, mortgage: 130 }, // 20
        { name: "FATAL DEVIATION!!", type: "corner" }, // 21
        { name: "Sirio", type: "property", color: "yellow", price: 280, baseRent: 24, rent1: 120, rent2: 360, rent3: 850, rent4: 1025, rentHotel: 1200, houseCost: 150, mortgage: 140 }, // 22
        { name: "Nebulosa de Orión", type: "property", color: "green", price: 300, baseRent: 26, rent1: 130, rent2: 390, rent3: 900, rent4: 1100, rentHotel: 1275, houseCost: 200, mortgage: 150 }, // 23
        { name: "PREGUNTA ESPACIAL", type: "action", subType: "question" }, // 24
        { name: "Nebulosa del Águila", type: "property", color: "green", price: 320, baseRent: 28, rent1: 150, rent2: 450, rent3: 1000, rent4: 1200, rentHotel: 1400, houseCost: 200, mortgage: 160 }, // 25
        { name: "Galaxia de Andrómeda", type: "property", color: "darkblue", price: 350, baseRent: 35, rent1: 175, rent2: 500, rent3: 1100, rent4: 1300, rentHotel: 1500, houseCost: 200, mortgage: 175 }, // 26
        { name: "Sagitario A*", type: "property", color: "darkblue", price: 400, baseRent: 50, rent1: 200, rent2: 600, rent3: 1400, rent4: 1700, rentHotel: 2000, houseCost: 200, mortgage: 200 } // 27
    ]
};
